### ISSUE TITLE
Feature request: Invoke a hook of another serverless plugin

### ISSUE THREAD

**Issue by noppa** [domdomegg/serverless-offline-watcher#6]
I recognize that coming here with this feature request is sort of asking for a solution to an _"XY problem"_, but here goes anyway.

Currently, serverless-offline doesn't have a built-in way to reload code after every file change. They have an option to reload code on every request, `--reloadHandler`, but that can make things very slow when your client makes lots of requests. I've raised this issue in here [serverless-offline/issues/1660](https://github.com/dherault/serverless-offline/issues/1660).

Meanwhile, I'm looking to solve this issue for me by watching file changes separately, and then manually making severless-offline invalidate its Worker thread cache. Luckily, they already expose a hook that does exactly this, `'offline:functionsUpdated'`. It just needs to invoked somehow. Serverless seems to provide a method `pluginManager.spawn(hookName)` to do this.

I was planning on making a plugin of my own that would watch for file changes and then spawn that event when it happens, but then noticed that your library is already 90% there.

I'm proposing a new option alongside the `command` option, `hooks`. Given a list of serverless plugin hook names, this plugin would invoke them whenever some of the watched files change. My use case is cache invalidation, but I think there could potentially be other use cases too, like automatically deploying the changed service to some test environment or validating its contents.

I have a possible implementation ready for this if you are interested in taking a PR for the feature.

**Comment by domdomegg** [comment]
This seems like a useful feature that fits in with the spirit of this plugin, so I'd be happy to take on a PR for this feature.

I've seen you've already opened #8 so will leave my comments there.
