### ISSUE TITLE
Feature request: Provide changed file path for the executed command

### ISSUE THREAD

**Issue by noppa** [domdomegg/serverless-offline-watcher#7]
The changed file path could be exposed in environment variables, letting the executed command know which file changed exactly. The changed file path could be useful if you want to rebuild just the changed file, for example.

I have a possible implementation ready for this if you are interested in taking a PR for the feature.

**Comment by domdomegg** [comment]
This seems like a useful feature that fits in with the spirit of this plugin, so I'd be happy to take on a PR for this feature.

I've seen you've already opened #8 so will leave my comments there.
